### PR TITLE
Feature: Implement Firebase Cloud Functions httpsCallable() Support

### PR DESCRIPTION
**Pull request by grandnexus**
Hi Kevin, I have added the relevant changes for firebase cloud functions httpscallable with test code and example.

### CODE REVIEW

**Comment by formatCvt** [comment]
Hi @grandnexus, great work!
One little thing - `data` parameter should be optional.
https://firebase.google.com/docs/reference/js/firebase.functions.HttpsCallable.html

**Comment by grandnexus** [comment]
> Hi @grandnexus, great work!
> One little thing - `data` parameter should be optional.
> https://firebase.google.com/docs/reference/js/firebase.functions.HttpsCallable.html

Hi @formatCvt, I have made `data` parameter optional. Thanks for the heads up!

**Comment by grandnexus** [comment]
> Please rebase on the latest HEAD – I've updated to the v6 API

Hi @kevmoo, I have rebased on the latest HEAD. Thanks! :)

**Comment by formatCvt** [comment]
Hi @grandnexus, thanks, we also need implementation for location selection (region) - https://firebase.google.com/docs/functions/locations#web

**Comment by kevmoo** [comment]
Closing in favor of https://github.com/FirebaseExtended/firebase-dart/pull/244

**Pull request closed without merging**
