### PR TITLE
Explicitly declare supported platforms

### PR DESCRIPTION
**Pull request by mit-mit**

### CODE REVIEW

**Comment by kevmoo** [comment]
Ugh...yeah, but the windows/mac/linux bits are so limited.

I should almost ditch those bits and just point folks to https://pub.dev/documentation/googleapis/latest/firestore.v1/firestore.v1-library.html

**Comment by mit-mit** [comment]
Your choice, but we should either: a) take this PR to be explicit about the platforms, or b) update readme etc. to only talk about web (which is the inferred platform tag).

**Comment by mit-mit** [comment]
@kevmoo so what's your prefernce?

**Comment by mit-mit** [comment]
Paging @kevmoo

**Comment by kevmoo** [comment]
I'm going to discontinue this package. It's no longer used by the flutter-fire things.

**Comment by kevmoo** [comment]
Discontinued the package!

**Pull request closed without merging**
